### ISSUE TITLE
Remove all /resources folders in individual TGG projects ...

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-tests#4]
and make sure that all references in tests are to the centralised resources folders in our single test suite project.

**Comment by anthonyanjorin** [comment]
or remove /resources in the centralised test suite project if that is easier.  Having both redundantly is definitely a problem (we should discuss why this is currently the case).

**Comment by FStolte** [comment]
Actually, I initially thought that having the resources remain in the TGG projects would be more difficult, which is why i copied them to the testsuite. Then however, I apparently used the resources from the TGG while forgetting about the copy. So if I'm not mistaken, it should be possible to just delete the resources folder in the testsuite project.

I will try this shortly and check if it affects any of the tests.

**Comment by FStolte** [comment]
This has already been solved a few days ago. Some tests used one location, some the other; now, all tests use the resources in the TGGs and the resource folder in the Testsuite has been deleted.
